### ISSUE TITLE
slv-cbftp CbGetSites seems to expect a different JSON body

### ISSUE THREAD

**Issue by hrxcodes** [silv3rr/sscripts.ga#3]
It looks like it's expecting the JSON body similar to the `/raw` endpoint. But `/sites` is just a JSON list  and not a array so it does not have either `successes` or `sites`.

https://github.com/silv3rr/sscripts.ga/blob/a7df2dc75a0c7ac1de7dbdfd4509053e6024df40/slv-cbapi.mrc#L378-L380

**Comment by silv3rr** [comment]
Hm, indeed...

For a quick fix, replace :
https://github.com/silv3rr/sscripts.ga/blob/a7df2dc75a0c7ac1de7dbdfd4509053e6024df40/slv-cbapi.mrc#L378-L391

With:

```
  var %cb_getsites = $regsubex($json(%cb_hn).string,^\[(.*)\]$,\1)
    if (%cb_debug >= 2) {
      echo -ast DEBUG: getsites $json(%cb_hn).debug
      echo -ast DEBUG: getsites cb_getsites= $+ %cb_getsites
    }
```

**Comment by silv3rr** [comment]
Fixed https://github.com/silv3rr/sscripts.ga/commit/0700e73436da97cb05472ea0f344a1bd83b8aef8
