### ISSUE TITLE
Error allocating stack memory line 1244 slv-cbapi.mrc

### ISSUE THREAD

**Issue by th3gr33n** [silv3rr/sscripts.ga#4]
Hi,

when i want to add the URL in the Settings TAB i get that error message in mIRC:
Error allocating stack memory line 1244 / 1240
also when adding the URL manually and issuing a command it returns the same error message.

It looks like as soon as the password is set i get this error.

**Comment by silv3rr** [comment]
No idea about that error tbh, try setting it in script or with `/CbSet url https://:passwd@host_ip:port` instead or see /CbHelp

**Comment by silv3rr** [comment]
Found the issue, `CbCheck` alias causes an infinite loop if api url and sites arent set yet.
Also noticed some more possible issues with the Settings dialog. Will fix in next version.

tmp fix for inf loop, change:
https://github.com/silv3rr/sscripts.ga/blob/2b3fec83039a46277fbc90514cbbbf5d3d26e97f/slv-cbapi.mrc#L1215

to:
`return $false`

**Comment by th3gr33n** [comment]
Thanks for reopening it.
can confirm the temp fix works for me.
